title: Huy Kha # your name (or website title) here
logo: "/images/linkedin.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Business Intelligence Analyst with 1+ year of experience in market research, business intelligence and data analytics, and a bachelor's degree in Business Management with First Class Honours from University of Greenwich.
  <br><br>
  <a href="https://www.linkedin.com/in/hellohuykha/">Visit my LinkedIn profile</a> 
  <br>
  <a href="https://medium.com/@hellohuykha/">Visit my Medium blog</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
